#
# Config for continual meta-test of ANML-like models on Omniglot. Just re-learns the final layer.
# This actually works on any model whose final layer is named as 'fc'.
#

# Dataset
dataset: omni
train_examples: 15
test_examples: 5

# Test Method
reinit_params: fc
opt_params: fc
classes: 600
lr: !include learning-rates.yml

# Reporting
eval_freq: 50
