#
# Continual meta-test on Omniglot.
# Learns last layer from scratch; fine-tunes the rest of the network.
#

# Dataset
dataset: omni
im_size: 84
train_examples: 15
test_examples: 5

# Test Method
reinit_params: classifier.mlp.2
opt_params: all
classes: 600
lr: !include learning-rates.yml

# Reporting
eval_freq: 50
