#
# Config for continual meta-test of Classifier-Basline models on Omniglot. Initializes final layer with LLS, then
# fine-tunes all layers.
#

# Dataset
dataset: omni
train_examples: 15
test_examples: 5

# Test Method
eval_method: seq
reinit_method: lstsq
reinit_params: classifier.linear
opt_params: all
classes: 600
lr: !include learning-rates.yml

# Reporting
eval_freq: 50
