#
# i.i.d. meta-test on Omniglot.
# Learns last layer from scratch; all other layers kept frozen.
#

# Dataset
dataset: omni
im_size: 84
train_examples: 15
test_examples: 5

# Test Method
eval_method: iid
reinit_params: classifier.mlp.2
opt_params: classifier.mlp.2
classes: 600
lr: !include learning-rates.yml

# Reporting
eval_freq: 5
