#
# Config for continual meta-test of Classifier-Basline models on Mini-ImageNet. Fine-tunes all layers.
#

# Dataset
dataset: miniimagenet
train_examples: 30
test_examples: 200

# Test Method
reinit_params: classifier.linear
opt_params: all
classes: 20
lr: 0.00007
