#
# Config for reproducing OML results on Mini-ImageNet.
#

# Dataset
dataset: miniimagenet
train_size: 500

# Training Configuration
batch_size: 1
num_batches: 20
train_cycles: 1
val_sample_size: 200
remember_size: 100
remember_only: false
inner_lr: 0.001
outer_lr: 0.001

epochs: 25000
seed: 1

# Model Architecture
model: classifier
model_name: oml
model_args:
  encoder: convnet
  encoder_args:
    num_blocks: 6
    num_filters: 256
    stride: [2, 1, 2, 1, 2, 2]
    padding: 0
    norm_type: null
    pool_size: null
  classifier: mlp-classifier
  classifier_args: {num_classes: 1000, hidden_layers: 1024}

# Optimization Configuration
inner_params: classifier
outer_params: all
output_layer: classifier.mlp.2

eval_steps: [10000, 25000]
eval:
  # WARNING: Currently these apply to the linear classifier, not the MLP classifier. Edit before launching.
  - no-sgd: !include eval-inet-zero-shot.yml
  - olft: !include eval-sweep-inet-1FC.yml
  - unfrozen: !include eval-sweep-inet-unfrozen.yml
  - lstsq-unfrozen: !include eval-sweep-inet-lstsq-unfrozen.yml
  - iid-olft: !include eval-sweep-inet-iid-1FC.yml
  - iid-unfrozen: !include eval-sweep-inet-iid-unfrozen.yml
  - iid-lstsq-unfrozen: !include eval-sweep-inet-iid-lstsq-unfrozen.yml
